import {
  ArrowUp,
  Sun,
  Moon,
  Laptop,
  Github,
  Twitter,
  Mail,
  Facebook,
  Youtube,
  Linkedin,
  Instagram,
  ChevronLeft,
  ChevronRight,
  Command,
  Check,
  X,
  Loader2,
  Search,
  Menu,
  User,
  LogOut,
  Settings,
  Bell,
  Heart,
  Star,
  Share,
  Bookmark,
  MessageSquare,
  Send,
  MoreVertical,
  MoreHorizontal,
  Trash,
  Edit,
  Copy,
  Link,
  ExternalLink,
  Filter,
  Sliders,
  Calendar,
  Clock,
  MapPin,
  Phone,
  Mail as MailIcon,
  Globe,
  Lock,
  Unlock,
  Eye,
  EyeOff,
  Key,
  CreditCard,
  Wallet,
  ShoppingCart,
  Package,
  Truck,
  Box,
  Archive,
  Inbox,
  Send as SendIcon,
  Download,
  Upload,
  Cloud,
  Database,
  Server,
  HardDrive,
  Network,
  Wifi,
  Bluetooth,
  Radio,
  Signal,
  Battery,
  Power,
  Zap,
  AlertCircle,
  AlertTriangle,
  CheckCircle,
  Info,
  HelpCircle,
  XCircle,
  Plus,
  Minus,
  ChevronUp,
  ChevronDown,
  ChevronsUp,
  ChevronsDown,
  ArrowRight,
  ArrowLeft,
  ArrowDown,
  ArrowUpRight,
  ArrowDownRight,
  ArrowUpLeft,
  ArrowDownLeft,
  Maximize,
  Minimize,
  Maximize2,
  Minimize2,
  Move,
  RotateCcw,
  RotateCw,
  RefreshCcw,
  RefreshCw,
  Repeat,
  Shuffle,
  SkipBack,
  SkipForward,
  FastForward,
  Rewind,
  Play,
  Pause,
  Square,
  Circle,
  Triangle,
  Hexagon,
  Octagon,
  Pentagon,
  Star as StarIcon,
  Heart as HeartIcon,
  ThumbsUp,
  ThumbsDown,
  Smile,
  Frown,
  Meh,
  Laugh,
  Angry,
  Bell as BellIcon,
  Bookmark as BookmarkIcon,
  Calendar as CalendarIcon,
  Camera,
  Check as CheckIcon,
  Clock as ClockIcon,
  Cloud as CloudIcon,
  Code,
  Coffee,
  CreditCard as CreditCardIcon,
  Database as DatabaseIcon,
  Download as DownloadIcon,
  Edit as EditIcon,
  ExternalLink as ExternalLinkIcon,
  Eye as EyeIcon,
  File,
  Filter as FilterIcon,
  Globe as GlobeIcon,
  HardDrive as HardDriveIcon,
  Headphones,
  Heart as HeartIcon2,
  HelpCircle as HelpCircleIcon,
  Home,
  Image,
  Inbox as InboxIcon,
  Info as InfoIcon,
  Key as KeyIcon,
  Laptop as LaptopIcon,
  Link as LinkIcon,
  List,
  Lock as LockIcon,
  LogOut as LogOutIcon,
  Mail as MailIcon2,
  MapPin as MapPinIcon,
  Maximize as MaximizeIcon,
  Menu as MenuIcon,
  MessageSquare as MessageSquareIcon,
  Mic,
  Moon as MoonIcon,
  MoreHorizontal as MoreHorizontalIcon,
  MoreVertical as MoreVerticalIcon,
  Move as MoveIcon,
  Music,
  Network as NetworkIcon,
  Package as PackageIcon,
  Phone as PhoneIcon,
  PieChart,
  Play as PlayIcon,
  Plus as PlusIcon,
  Power as PowerIcon,
  Printer,
  Radio as RadioIcon,
  RefreshCcw as RefreshCcwIcon,
  RefreshCw as RefreshCwIcon,
  Repeat as RepeatIcon,
  Rewind as RewindIcon,
  RotateCcw as RotateCcwIcon,
  RotateCw as RotateCwIcon,
  Save,
  Scissors,
  Search as SearchIcon,
  Send as SendIcon2,
  Server as ServerIcon,
  Settings as SettingsIcon,
  Share as ShareIcon,
  Shield,
  ShoppingCart as ShoppingCartIcon,
  Shuffle as ShuffleIcon,
  SkipBack as SkipBackIcon,
  SkipForward as SkipForwardIcon,
  Sliders as SlidersIcon,
  Smartphone,
  Smile as SmileIcon,
  Speaker,
  Square as SquareIcon,
  Star as StarIcon2,
  Sun as SunIcon,
  Tablet,
  Tag,
  Target,
  Terminal,
  Thermometer,
  ThumbsDown as ThumbsDownIcon,
  ThumbsUp as ThumbsUpIcon,
  ToggleLeft,
  ToggleRight,
  Trash as TrashIcon,
  Truck as TruckIcon,
  Tv,
  Type,
  Umbrella,
  Underline,
  Unlock as UnlockIcon,
  Upload as UploadIcon,
  User as UserIcon,
  Users,
  Video,
  VideoOff,
  Voicemail,
  Volume,
  Volume1,
  Volume2,
  VolumeX,
  Wallet as WalletIcon,
  Wifi as WifiIcon,
  Wind,
  X as XIcon,
  XCircle as XCircleIcon,
  Zap as ZapIcon,
  ZoomIn,
  ZoomOut,
  Chrome,
} from "lucide-react"

export const Icons = {
  sun: Sun,
  moon: Moon,
  laptop: Laptop,
  github: Github,
  twitter: Twitter,
  mail: Mail,
  facebook: Facebook,
  youtube: Youtube,
  linkedin: Linkedin,
  instagram: Instagram,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  command: Command,
  check: Check,
  x: X,
  spinner: Loader2,
  search: Search,
  menu: Menu,
  user: User,
  logOut: LogOut,
  settings: Settings,
  bell: Bell,
  heart: Heart,
  star: Star,
  share: Share,
  bookmark: Bookmark,
  messageSquare: MessageSquare,
  send: Send,
  moreVertical: MoreVertical,
  moreHorizontal: MoreHorizontal,
  trash: Trash,
  edit: Edit,
  copy: Copy,
  link: Link,
  externalLink: ExternalLink,
  filter: Filter,
  sliders: Sliders,
  calendar: Calendar,
  clock: Clock,
  mapPin: MapPin,
  phone: Phone,
  mailIcon: MailIcon,
  globe: Globe,
  lock: Lock,
  unlock: Unlock,
  eye: Eye,
  eyeOff: EyeOff,
  key: Key,
  creditCard: CreditCard,
  wallet: Wallet,
  shoppingCart: ShoppingCart,
  package: Package,
  truck: Truck,
  box: Box,
  archive: Archive,
  inbox: Inbox,
  sendIcon: SendIcon,
  download: Download,
  upload: Upload,
  cloud: Cloud,
  database: Database,
  server: Server,
  hardDrive: HardDrive,
  network: Network,
  wifi: Wifi,
  bluetooth: Bluetooth,
  radio: Radio,
  signal: Signal,
  battery: Battery,
  power: Power,
  zap: Zap,
  alertCircle: AlertCircle,
  alertTriangle: AlertTriangle,
  checkCircle: CheckCircle,
  info: Info,
  helpCircle: HelpCircle,
  xCircle: XCircle,
  plus: Plus,
  minus: Minus,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  chevronsUp: ChevronsUp,
  chevronsDown: ChevronsDown,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  arrowDown: ArrowDown,
  arrowUp: ArrowUp,
  arrowUpRight: ArrowUpRight,
  arrowDownRight: ArrowDownRight,
  arrowUpLeft: ArrowUpLeft,
  arrowDownLeft: ArrowDownLeft,
  maximize: Maximize,
  minimize: Minimize,
  maximize2: Maximize2,
  minimize2: Minimize2,
  move: Move,
  rotateCcw: RotateCcw,
  rotateCw: RotateCw,
  refreshCcw: RefreshCcw,
  refreshCw: RefreshCw,
  repeat: Repeat,
  shuffle: Shuffle,
  skipBack: SkipBack,
  skipForward: SkipForward,
  fastForward: FastForward,
  rewind: Rewind,
  play: Play,
  pause: Pause,
  square: Square,
  circle: Circle,
  triangle: Triangle,
  hexagon: Hexagon,
  octagon: Octagon,
  pentagon: Pentagon,
  starIcon: StarIcon,
  heartIcon: HeartIcon,
  thumbsUp: ThumbsUp,
  thumbsDown: ThumbsDown,
  smile: Smile,
  frown: Frown,
  meh: Meh,
  laugh: Laugh,
  angry: Angry,
  bellIcon: BellIcon,
  bookmarkIcon: BookmarkIcon,
  calendarIcon: CalendarIcon,
  camera: Camera,
  checkIcon: CheckIcon,
  clockIcon: ClockIcon,
  cloudIcon: CloudIcon,
  code: Code,
  coffee: Coffee,
  creditCardIcon: CreditCardIcon,
  databaseIcon: DatabaseIcon,
  downloadIcon: DownloadIcon,
  editIcon: EditIcon,
  externalLinkIcon: ExternalLinkIcon,
  eyeIcon: EyeIcon,
  file: File,
  filterIcon: FilterIcon,
  globeIcon: GlobeIcon,
  hardDriveIcon: HardDriveIcon,
  headphones: Headphones,
  heartIcon2: HeartIcon2,
  helpCircleIcon: HelpCircleIcon,
  home: Home,
  image: Image,
  inboxIcon: InboxIcon,
  infoIcon: InfoIcon,
  keyIcon: KeyIcon,
  laptopIcon: LaptopIcon,
  linkIcon: LinkIcon,
  list: List,
  lockIcon: LockIcon,
  logOutIcon: LogOutIcon,
  mailIcon2: MailIcon2,
  mapPinIcon: MapPinIcon,
  maximizeIcon: MaximizeIcon,
  menuIcon: MenuIcon,
  messageSquareIcon: MessageSquareIcon,
  mic: Mic,
  moonIcon: MoonIcon,
  moreHorizontalIcon: MoreHorizontalIcon,
  moreVerticalIcon: MoreVerticalIcon,
  moveIcon: MoveIcon,
  music: Music,
  networkIcon: NetworkIcon,
  packageIcon: PackageIcon,
  phoneIcon: PhoneIcon,
  pieChart: PieChart,
  playIcon: PlayIcon,
  plusIcon: PlusIcon,
  powerIcon: PowerIcon,
  printer: Printer,
  radioIcon: RadioIcon,
  refreshCcwIcon: RefreshCcwIcon,
  refreshCwIcon: RefreshCwIcon,
  repeatIcon: RepeatIcon,
  rewindIcon: RewindIcon,
  rotateCcwIcon: RotateCcwIcon,
  rotateCwIcon: RotateCwIcon,
  save: Save,
  scissors: Scissors,
  searchIcon: SearchIcon,
  sendIcon2: SendIcon2,
  serverIcon: ServerIcon,
  settingsIcon: SettingsIcon,
  shareIcon: ShareIcon,
  shield: Shield,
  shoppingCartIcon: ShoppingCartIcon,
  shuffleIcon: ShuffleIcon,
  skipBackIcon: SkipBackIcon,
  skipForwardIcon: SkipForwardIcon,
  slidersIcon: SlidersIcon,
  smartphone: Smartphone,
  smileIcon: SmileIcon,
  speaker: Speaker,
  squareIcon: SquareIcon,
  starIcon2: StarIcon2,
  sunIcon: SunIcon,
  tablet: Tablet,
  tag: Tag,
  target: Target,
  terminal: Terminal,
  thermometer: Thermometer,
  thumbsDownIcon: ThumbsDownIcon,
  thumbsUpIcon: ThumbsUpIcon,
  toggleLeft: ToggleLeft,
  toggleRight: ToggleRight,
  trashIcon: TrashIcon,
  truckIcon: TruckIcon,
  tv: Tv,
  type: Type,
  umbrella: Umbrella,
  underline: Underline,
  unlockIcon: UnlockIcon,
  uploadIcon: UploadIcon,
  userIcon: UserIcon,
  users: Users,
  video: Video,
  videoOff: VideoOff,
  voicemail: Voicemail,
  volume: Volume,
  volume1: Volume1,
  volume2: Volume2,
  volumeX: VolumeX,
  walletIcon: WalletIcon,
  wifiIcon: WifiIcon,
  wind: Wind,
  xIcon: XIcon,
  xCircleIcon: XCircleIcon,
  zapIcon: ZapIcon,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  google: Chrome,
} 